include ../../global_config

OBJS = $(OBJDIR)/colorbalance.o  \
	$(OBJDIR)/colorbalancewindow.o

PLUGIN = colorbalance

include ../../plugin_config

$(OBJDIR)/colorbalance.o: colorbalance.C
$(OBJDIR)/colorbalancewindow.o: colorbalancewindow.C
