include ../../global_config

OBJS = $(OBJDIR)/reverb.o  \
	$(OBJDIR)/reverbwindow.o

PLUGIN = reverb

include ../../plugin_config

$(OBJDIR)/reverb.o: reverb.C
$(OBJDIR)/reverbwindow.o: reverbwindow.C
