include ../../global_config

OBJS = $(OBJDIR)/timeavg.o  \
	$(OBJDIR)/timeavgwindow.o

PLUGIN = timeavg

include ../../plugin_config

$(OBJDIR)/timeavg.o: timeavg.C
$(OBJDIR)/timeavgwindow.o: timeavgwindow.C



