include ../../global_config

OBJS = $(OBJDIR)/timestretchrt.o \
	../timestretch/$(OBJDIR)/timestretchengine.o

PLUGIN = timestretchrt

include ../../plugin_config


$(OBJDIR)/timestretchrt.o: timestretchrt.C



