include ../../global_config

PLUGIN = blondtheme
OBJS = $(OBJDIR)/blondtheme.o
OUTPUT_THEME = $(OUTPUT)

CFLAGS += -I../../$(AVC_DIR) -I../../$(LIBRAW_DIR)

include ../../plugin_config

$(OBJDIR)/blondtheme.o: blondtheme.C

