include ../../global_config

OBJS := \
	$(OBJDIR)/downsampleengine.o \
	$(OBJDIR)/motionscan.o \
	$(OBJDIR)/motion.o \
	$(OBJDIR)/motionwindow.o

PLUGIN = motion2

include ../../plugin_config

$(OBJDIR)/downsampleengine.o: downsampleengine.C
$(OBJDIR)/motion.o: motion.C
$(OBJDIR)/motionscan.o: motionscan.C
$(OBJDIR)/motionwindow.o: motionwindow.C
